// This file contains all user-facing English text for localization/translation.
// To add a new language, copy this structure and translate the values.

const language = {
  common: {
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    loading: 'Loading...',
    error: 'An error occurred. Please try again.',
    noResults: 'No results found.',
    submit: 'Submit',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    required: 'This field is required.',
    optional: 'Optional',
    select: 'Select',
    selectOption: 'Select an option',
    or: 'or',
    and: 'and',
    more: 'More',
    less: 'Less',
    viewAll: 'View All',
    viewMore: 'View More',
    viewDetails: 'View Details',
    show: 'Show',
    hide: 'Hide',
    remove: 'Remove',
    add: 'Add',
    upload: 'Upload',
    download: 'Download',
    filter: 'Filter',
    reset: 'Reset',
    apply: 'Apply',
    clear: 'Clear',
    actions: 'Actions',
    settings: 'Settings',
    help: 'Help',
    contactUs: 'Contact Us',
    callUs: 'Call Us',
    aboutUs: 'About Us',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    careers: 'Careers',
    advertising: 'Advertising',
    company: 'Company',
    support: 'Support',
    languages: 'Languages',
    switchToArabic: 'Switch to Arabic',
    copyright: '© 888Market 2025, All Rights Reserved.',
    whatsapp: 'Whatsapp',
    english: 'English',
    arabic: 'Arabic',
    postAdNow: 'Post Ad Now',
    saveAsDraft: 'Save as Draft',
    continuePostingAd: 'Continue Posting Ad',
    placeOrder: 'Place Order',
    continueToPayment: 'Continue to Payment',
    reviewYourOrder: 'Review Your Order',
    orderSummary: 'Order Summary',
    shipping: 'Shipping',
    payment: 'Payment',
    review: 'Review',
    items: 'Items',
    shippingInformation: 'Shipping Information',
    paymentMethod: 'Payment Method',
    creditDebitCard: 'Credit/Debit Card',
    cardNumber: 'Card Number *',
    expiryDate: 'Expiry Date *',
    cvv: 'CVV *',
    nameOnCard: 'Name on Card *',
    firstName: 'First Name *',
    lastName: 'Last Name *',
    emailAddress: 'Email Address *',
    phoneNumber: 'Phone Number *',
    address: 'Address *',
    city: 'City *',
    state: 'State/Emirate *',
    zipPostalCode: 'Zip/Postal Code *',
    country: 'Country *',
    orderPlaced: 'Order placed successfully!',
    orderFailed: 'Order failed. Please try again.',
    myCart: 'My Cart',
    cartEmpty: 'Your cart items will appear here.',
    workingOnPayments: "We're working hard to bring you more payment options.",
    stayTuned: 'Stay tuned for updates and thank you for your patience!',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    discount: 'Discount',
    stock: 'Stock *',
    currency: 'Currency',
    originalPrice: 'Original Price *',
    discountedPrice: 'Discounted Price',
    productImages: 'Product Images',
    addImage: 'Add Image',
    uploadImagesInfo:
      'Upload up to 10 images. First image will be the main photo.',
    basicInformation: 'Basic Information',
    productTitle: 'Product Title *',
    description: 'Description *',
    provideDescription: 'Provide detailed description...',
    category: 'Category *',
    selectCategory: 'Select Category',
    subcategory: 'Subcategory *',
    selectSubcategory: 'Select Subcategory',
    locationContact: 'Location & Contact Information',
    location: 'Location *',
    enterLocation: 'Enter your city, state or full address',
    contactName: 'Contact Name *',
    yourName: 'Your name',
    yourPhoneNumber: 'Your phone number',
    yourEmail: 'Your email address',
    pricingStock: 'Pricing & Stock',
    postAdSuccess: 'Product has been successfully uploaded.',
    postAdError: 'Error trying to upload your product.',
    noAds: "You haven't placed any ads yet",
    postAd: 'Post ad now',
    featuredListing: 'Featured Listing',
    popularCategories: 'Popular Categories',
    furnitureForSale: 'Furniture for sale in ethiopia • 32,498 Ads',
    sortDefault: 'Sort: Default',
    saveSearch: 'Save Search',
    searchPlaceholder: 'What are you looking for?',
    heroTitle: 'Your favorite place',
    heroSubtitle: 'for great deals on secondhand items',
    browseNow: 'Browse Now',
    exploreNow: 'Explore Now',
    discoverAgents: 'Discover Agents and Agencies!',
    connectWithPartners: 'Connect with our partners to find your ideal home!',
    introducingNewProducts: 'Introducing New Products',
    getAccessLatest: 'Get access to the latest releases',
    new: 'NEW',
    viewMoreCategories: 'View More Categories',
    jobsByQualification: 'Jobs By Qualification',
    fullTime: 'Full Time',
    birr: 'Birr',
    salesMan: 'Salesman and Sales Lady',
    martCashier: 'Mart Cashier',
    waiter: 'Waiter or Waitress',
    receptionist: 'Receptionist Male/Female',
    descriptionSection: 'Description',
    noDescription: 'No description available',
    slugSection: 'Slug',
    notAvailable: 'N/A',
    customerSupport: 'Customer Support',
    helpCenter: 'Help Center',
    status: 'Status:',
    shipped: 'Shipped',
    itemsLabel: 'Items:',
    tracking: 'Tracking:',
    typeMessage: 'Type your message...',
    send: 'Send',
    quickReplies: [
      'Where is my order?',
      'How do I return an item?',
      'Can I change my shipping address?',
      'Do you offer international shipping?',
    ],
    quickActions: {
      track: 'I need help tracking my order. Can you help me find the status?',
      payment: "I'm having issues with my payment. Can you assist me?",
      returns: 'I need to return an item. How do I start the return process?',
      help: 'I need general help with my account and orders.',
    },
    chatAutoReplies: {
      order:
        "Your order is currently being processed and should be shipped within 1-2 business days. You'll receive a tracking number via email once it ships.",
      return:
        "We offer hassle-free returns within 30 days of purchase. You can initiate a return from your account's order history page or I can help you start the process now.",
      discount:
        "I'd be happy to check for available promotions! You can use code WELCOME15 for 15% off your first order. Would you like me to suggest some current deals?",
      default:
        "Thank you for your message. I'll help you with that right away. Could you please provide a bit more information so I can better assist you?",
    },
    chatAlerts: {
      callSupport: 'Calling support at 1-800-SHOP-EASE...',
      fileUpload: 'File upload feature coming soon!',
      imageUpload: 'Image upload feature coming soon!',
      emojiPicker: 'Emoji picker coming soon!',
    },
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    signUp: 'Sign up',
    createAccount: 'Create your account',
    signUpToGetStarted: 'Sign up to get started',
    continueWithGoogle: 'Continue with Google',
    orContinueWith: 'Or continue with',
    signUpWithEmail: 'Sign up with Email',
    errorMessage: 'An error occurred. Please try again.',
    // Add more as needed from the app
  },
};

export default language;
